-- MySQL Script generated by MySQL Workbench
-- dom 02 jul 2023 11:00:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema FinalDMU
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FinalDMU` ;

-- -----------------------------------------------------
-- Schema FinalDMU
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FinalDMU` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `FinalDMU` ;

-- -----------------------------------------------------
-- Table `FinalDMU`.`tbl_centros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalDMU`.`tbl_centro` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `centro` VARCHAR(60) NOT NULL,
  `codigo_sace` VARCHAR(12) NOT NULL,
  `administracion` VARCHAR(15) NOT NULL,
  `zona` VARCHAR(10) NOT NULL,
  `nivel` VARCHAR(15) NOT NULL,
  `ciclo` VARCHAR(30) NOT NULL,
  `jornada` VARCHAR(40) NOT NULL,
  `cobertura` VARCHAR(12) NOT NULL,
  `matricula` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `FinalDMU`.`tbl_resultado_final`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinalDMU`.`tbl_resultado_final` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `grado` VARCHAR(15) NOT NULL,
  `inicial_n` SMALLINT(3) NOT NULL,
  `inicial_v` SMALLINT(3) NOT NULL,
  `inicial_t` SMALLINT(3) NOT NULL,
  `final_n` SMALLINT(3) NOT NULL,
  `final_v` SMALLINT(3) NOT NULL,
  `final_t` SMALLINT(3) NOT NULL,
  `ingre_n` SMALLINT(3) NOT NULL,
  `ingre_v` SMALLINT(3) NOT NULL,
  `ingre_t` SMALLINT(3) NOT NULL,
  `trasla_n` SMALLINT(3) NOT NULL,
  `trasla_v` SMALLINT(3) NOT NULL,
  `trasla_t` SMALLINT(3) NOT NULL,
  `deser_n` SMALLINT(3) NOT NULL,
  `deser_v` SMALLINT(3) NOT NULL,
  `deser_t` SMALLINT(3) NOT NULL,
  `evalu_n` SMALLINT(3) NOT NULL,
  `evalu_v` SMALLINT(3) NOT NULL,
  `evalu_t` SMALLINT(3) NOT NULL,
  `inic_n` SMALLINT(3) NOT NULL,
  `inic_v` SMALLINT(3) NOT NULL,
  `inic_t` SMALLINT(3) NOT NULL,
  `basi_n` SMALLINT(3) NOT NULL,
  `basi_v` SMALLINT(3) NOT NULL,
  `basi_t` SMALLINT(3) NOT NULL,
  `avan_n` SMALLINT(3) NOT NULL,
  `avan_v` SMALLINT(3) NOT NULL,
  `avan_t` SMALLINT(3) NOT NULL,
  `exce_n` SMALLINT(3) NOT NULL,
  `exce_v` SMALLINT(3) NOT NULL,
  `exce_t` SMALLINT(3) NOT NULL,
  `codigo_centro` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  CONSTRAINT `fk_tbl_resultado_final_1`
    FOREIGN KEY (`codigo_centro`)
    REFERENCES `FinalDMU`.`tbl_centro` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;

CREATE INDEX `fk_tbl_resultado_final_1_idx` ON `FinalDMU`.`tbl_resultado_final` (`codigo_centro` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
