CREATE TABLE `tbl_matricula_final_edad` (
`codigo` int(11) NOT NULL AUTO_INCREMENT,
`grado` varchar(15) NOT NULL,
`edad_menos_6_n` smallint(3) NOT NULL,
`edad_menos_6_v` smallint(3) NOT NULL,
`edad_menos_6_t` smallint(3) NOT NULL,
`edad_6_n` smallint(3) NOT NULL,
`edad_6_v` smallint(3) NOT NULL,
`edad_6_t` smallint(3) NOT NULL,
`edad_7_n` smallint(3) NOT NULL,
`edad_7_v` smallint(3) NOT NULL,
`edad_7_t` smallint(3) NOT NULL,
`edad_8_n` smallint(3) NOT NULL,
`edad_8_v` smallint(3) NOT NULL,
`edad_8_t` smallint(3) NOT NULL,
`edad_9_n` smallint(3) NOT NULL,
`edad_9_v` smallint(3) NOT NULL,
`edad_9_t` smallint(3) NOT NULL,
`edad_10_n` smallint(3) NOT NULL,
`edad_10_v` smallint(3) NOT NULL,
`edad_10_t` smallint(3) NOT NULL,
`edad_11_n` smallint(3) NOT NULL,
`edad_11_v` smallint(3) NOT NULL,
`edad_11_t` smallint(3) NOT NULL,
`edad_12_n` smallint(3) NOT NULL,
`edad_12_v` smallint(3) NOT NULL,
`edad_12_t` smallint(3) NOT NULL,
`edad_13_n` smallint(3) NOT NULL,
`edad_13_v` smallint(3) NOT NULL,
`edad_13_t` smallint(3) NOT NULL,
`edad_14_n` smallint(3) NOT NULL,
`edad_14_v` smallint(3) NOT NULL,
`edad_14_t` smallint(3) NOT NULL,
`edad_15_mas_n` smallint(3) NOT NULL,
`edad_15_mas_v` smallint(3) NOT NULL,
`edad_15_mas_t` smallint(3) NOT NULL,
`codigo_centro` int(11) NOT NULL,
PRIMARY KEY (`codigo`),
  KEY `fk_tbl_matricula_final_edad_1_idx` (`codigo_centro`),
  CONSTRAINT `fk_tbl_matricula_final_edad_1` FOREIGN KEY (`codigo_centro`) REFERENCES `tbl_centro` (`codigo`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci